// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqs0yOQzq3S6goOIEaRlsmHUbwtjaXa3Y',
    appId: '1:199384030415:web:2344635c6b562ca7dbabba',
    messagingSenderId: '199384030415',
    projectId: 'smartbins-14eb2',
    authDomain: 'smartbins-14eb2.firebaseapp.com',
    databaseURL: 'https://smartbins-14eb2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartbins-14eb2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5cE0LAZaWXwriko4yQyIl4OL0dV8H0O4',
    appId: '1:199384030415:android:39111fcbb7d303cddbabba',
    messagingSenderId: '199384030415',
    projectId: 'smartbins-14eb2',
    databaseURL: 'https://smartbins-14eb2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartbins-14eb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9sH13GfSWBIgy4OtP7jQUbDhqQoyewpo',
    appId: '1:199384030415:ios:2df49c1cd1a107a0dbabba',
    messagingSenderId: '199384030415',
    projectId: 'smartbins-14eb2',
    databaseURL: 'https://smartbins-14eb2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartbins-14eb2.appspot.com',
    iosBundleId: 'com.example.smartBinsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9sH13GfSWBIgy4OtP7jQUbDhqQoyewpo',
    appId: '1:199384030415:ios:0004561528c99f9edbabba',
    messagingSenderId: '199384030415',
    projectId: 'smartbins-14eb2',
    databaseURL: 'https://smartbins-14eb2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartbins-14eb2.appspot.com',
    iosBundleId: 'com.example.smartBinsFlutter.RunnerTests',
  );
}
